name: Build latest docker and push
on:
  push:
    branches: [ main ]
jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: docker hub login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: build docker image
        run: docker build -t sebastiannoelluebke/webhooks-bridge:latest -t sebastiannoelluebke/webhooks-bridge:$GITHUB_SHA .
      - name: push
        run: docker push sebastiannoelluebke/webhooks-bridge --all-tags